.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. IoP_qt test_IoP_qt
clean: FORCE
	$(MAKE) -C .. IoP_qt_clean test_IoP_qt_clean
check: FORCE
	$(MAKE) -C .. test_IoP_qt_check
IoP-qt IoP-qt.exe: FORCE
	 $(MAKE) -C .. IoP_qt
